// ─── Value Attribution Ledger ─────────────────────────────────────────────────
// Tracks measurable £ value generated by each StrydeOS module.
// "This product saved / made your clinic £X" — defensible, auditable, low-quibble.
//
// Firestore path: clinics/{clinicId}/value_events/{eventId}
// Summaries:      clinics/{clinicId}/value_summaries/{period}  (e.g. "2026-Q1", "2026-03")

// ── Source Module ────────────────────────────────────────────

export type ValueModule = "ava" | "pulse" | "intelligence";

// ── Attribution Event Types ─────────────────────────────────

export type ValueEventType =
  // Ava — Revenue Rescued
  | "AVA_AFTER_HOURS_BOOKING"      // Call outside reception hours → booking confirmed
  | "AVA_OVERFLOW_BOOKING"         // Call answered when lines busy → booking confirmed
  | "AVA_CALL_HANDLED"             // Any call handled (receptionist-equivalent labour saved)

  // Pulse — Revenue Recovered
  | "PULSE_DROPOUT_REENGAGED"      // At-risk patient nudged → rebooked within attribution window
  | "PULSE_DNA_RECOVERED"          // Patient DNA'd → Pulse rebooking prompt → rebooked
  | "PULSE_COURSE_COMPLETION"      // Patient nudged to complete course → completed remaining sessions
  | "PULSE_REVIEW_GENERATED"       // Review prompt → patient posted Google/Trustpilot review

  // Intelligence — Revenue Gained
  | "INTEL_METRIC_IMPROVEMENT"     // Core KPI improved vs 90-day baseline (rolling)
  | "INTEL_INSIGHT_ACTED_ON"       // Insight event viewed → action taken → outcome improved
  | "INTEL_GHOST_REACTIVATED";     // Ghost patient surfaced by Intelligence → reactivated

// ── Confidence Level ────────────────────────────────────────

export type AttributionConfidence = "high" | "medium" | "low";

// high   = direct causal chain (Ava answered call → booking created; Pulse nudged → patient rebooked)
// medium = strong correlation (metric improved after Intelligence adoption; review posted after prompt)
// low    = indirect / shared attribution (general improvement trend)

// ── Value Event ─────────────────────────────────────────────

export interface ValueEvent {
  id: string;
  clinicId: string;
  module: ValueModule;
  type: ValueEventType;
  confidence: AttributionConfidence;

  // The money
  valuePence: number;               // Conservative £ estimate (always round DOWN)
  valueCalculation: string;         // Human-readable formula, e.g. "3 remaining sessions × £65 = £195"

  // Context
  title: string;                    // e.g. "Pulse re-engaged Emma Thompson"
  description: string;              // e.g. "Patient was 12 days without rebooking (mid-course, session 3/6)"

  // Linkage (optional — for audit trail)
  patientId?: string;
  patientName?: string;
  clinicianId?: string;
  clinicianName?: string;
  appointmentId?: string;           // The booking that resulted from the attribution
  commsLogEntryId?: string;         // The Pulse message that triggered the action
  callLogId?: string;               // The Ava call that triggered the booking
  insightEventId?: string;          // The Intelligence insight that was acted on

  // Timestamps
  triggeredAt: string;              // When the StrydeOS action happened (nudge sent, call answered)
  attributedAt: string;             // When the outcome was confirmed (booking created, review posted)
  createdAt: string;                // When this ledger entry was written

  // Metadata
  metadata: Record<string, unknown>;
}

// ── Module Summary ──────────────────────────────────────────

export interface ModuleValueSummary {
  module: ValueModule;
  totalValuePence: number;
  eventCount: number;
  highConfidenceValuePence: number;
  highConfidenceCount: number;
  topEventType: ValueEventType;
  topEventTypeCount: number;
}

// ── Period Summary ──────────────────────────────────────────
// Pre-computed and cached for fast dashboard rendering.
// Firestore path: clinics/{clinicId}/value_summaries/{period}

export interface ValueSummary {
  id: string;                       // Period key: "2026-03" or "2026-Q1"
  clinicId: string;
  periodType: "month" | "quarter";
  periodStart: string;              // ISO date
  periodEnd: string;                // ISO date

  // Totals
  totalValuePence: number;
  totalEvents: number;
  highConfidenceValuePence: number;

  // Per-module breakdown
  ava: ModuleValueSummary;
  pulse: ModuleValueSummary;
  intelligence: ModuleValueSummary;

  // ROI calculation (vs subscription cost)
  subscriptionCostPence: number;    // Monthly cost in pence (e.g. 40000 = £400)
  roiMultiple: number;              // totalValuePence / subscriptionCostPence
  netValuePence: number;            // totalValuePence - subscriptionCostPence

  // Headline stats for quick rendering
  patientsReengaged: number;        // Pulse dropout recoveries
  callsHandled: number;             // Ava total calls
  bookingsFromAva: number;          // Ava-attributed bookings
  reviewsGenerated: number;         // Pulse-prompted reviews
  insightsActedOn: number;          // Intelligence insights with outcomes
  ghostsReactivated: number;        // Intelligence ghost patient recoveries

  computedAt: string;
}

// ── Deep Metrics (derived from existing data) ───────────────
// These sit alongside WeeklyStats but provide the "intelligence" layer.

export interface RetentionStep {
  session: number;                  // 1, 2, 3, 4, 5, 6+
  patientsReached: number;          // Count who made it to this session
  percentOfInitial: number;         // patientsReached / totalIAs
  dropoffFromPrevious: number;      // % who dropped between this and previous step
  revenueLostPence: number;         // Dropoff × remaining sessions × session rate
}

export interface DeepMetrics {
  clinicId: string;
  clinicianId: string;              // "all" for clinic-wide
  weekStart: string;

  // Cost of Empty Chair
  costOfEmptyChairPence: number;    // (DNAs + unfilled slots) × avg session rate
  costOfEmptyChairAnnualisedPence: number;
  dnaSlots: number;
  unfilledSlots: number;

  // Patient Retention Curve
  retentionCurve: RetentionStep[];  // Session 1 through 6+
  biggestDropoffSession: number;    // Which session number loses the most patients
  biggestDropoffPercent: number;

  // Net Growth
  newPatients: number;              // New IAs this period
  dischargedPatients: number;       // Properly discharged this period
  ghostPatients: number;            // >30 days no activity, not discharged
  netGrowth: number;                // newPatients - dischargedPatients

  // Rebooking Lag
  avgRebookingLagDays: number;      // Average days between consecutive sessions
  medianRebookingLagDays: number;
  patientsOverThreshold: number;    // Patients with lag > 14 days (dropout risk zone)

  // Discharge Quality
  properDischarges: number;         // Completed course + documented discharge
  ghostDischarges: number;          // Faded away without discharge
  dischargeQualityRate: number;     // properDischarges / (proper + ghost)

  // Revenue Per Available Hour
  revenuePerAvailableHourPence?: number;  // Only if capacity data available
  revenuePerDeliveredHourPence: number;   // Total revenue / total booked hours

  // Patient Lifetime Value
  avgLifetimeValuePence: number;    // Avg total revenue per patient journey (IA → discharge)
  medianLifetimeValuePence: number;
  topReferralSourceByLtv?: string;  // Which referral source produces highest-LTV patients
  insuranceLtvPence?: number;       // Avg LTV for insured patients
  selfPayLtvPence?: number;         // Avg LTV for self-pay patients

  computedAt: string;
}

// ── Ava Attribution Config ──────────────────────────────────

export interface AvaAttributionConfig {
  /** Hours considered "after-hours" for attribution (e.g. before 9, after 17:30). */
  receptionStartHour: number;       // default: 9
  receptionEndHour: number;         // default: 17.5 (17:30)
  /** Equivalent hourly cost of a receptionist for labour-saved calculation. */
  receptionistHourlyRatePence: number; // default: 1200 (£12/hr)
  /** Average call duration in minutes for labour calculation. */
  avgCallDurationMinutes: number;   // default: 4
}

export const DEFAULT_AVA_ATTRIBUTION_CONFIG: AvaAttributionConfig = {
  receptionStartHour: 9,
  receptionEndHour: 17.5,
  receptionistHourlyRatePence: 1200,
  avgCallDurationMinutes: 4,
};

// ── Pulse Attribution Config ────────────────────────────────

export interface PulseAttributionConfig {
  /** Days after Pulse nudge within which a rebooking is attributed to Pulse. */
  attributionWindowDays: number;    // default: 3
  /** Conservative £ value assigned per Google/Trustpilot review generated. */
  reviewValuePence: number;         // default: 7500 (£75)
}

export const DEFAULT_PULSE_ATTRIBUTION_CONFIG: PulseAttributionConfig = {
  attributionWindowDays: 3,
  reviewValuePence: 7500,
};
