/**
 * OAuth 2.0 token endpoint for the stryde-ops MCP connector.
 *
 * Supports two grant types:
 *
 * 1. client_credentials — The "client secret" is MCP_BEARER_SECRET. The issued
 *    access token is the secret itself, so verifyBearer() in the MCP route
 *    continues to work unchanged.
 *
 * 2. authorization_code — Used by claude.ai custom connectors (PKCE flow).
 *    The code is a stateless signed token generated by /api/mcp/authorize.
 *    Verifies HMAC signature + expiry + PKCE code_verifier, then issues the
 *    same MCP_BEARER_SECRET as the access token.
 */

import { NextRequest, NextResponse } from "next/server";
import crypto from "node:crypto";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function tokenError(error: string, status = 400) {
  return NextResponse.json({ error }, { status });
}

export async function POST(request: NextRequest): Promise<NextResponse> {
  let grantType: string | null = null;
  let clientSecret: string | null = null;
  let code: string | null = null;
  let codeVerifier: string | null = null;

  const contentType = request.headers.get("content-type") ?? "";

  if (contentType.includes("application/x-www-form-urlencoded")) {
    const form = await request.formData();
    grantType = form.get("grant_type") as string | null;
    clientSecret = form.get("client_secret") as string | null;
    code = form.get("code") as string | null;
    codeVerifier = form.get("code_verifier") as string | null;
    // Also accept client_secret_basic via Authorization header
    if (!clientSecret) {
      const basic = request.headers.get("authorization") ?? "";
      if (basic.startsWith("Basic ")) {
        const decoded = Buffer.from(basic.slice(6), "base64").toString("utf8");
        clientSecret = decoded.split(":")[1] ?? null;
      }
    }
  } else {
    try {
      const body = (await request.json()) as Record<string, string>;
      grantType = body.grant_type ?? null;
      clientSecret = body.client_secret ?? null;
      code = body.code ?? null;
      codeVerifier = body.code_verifier ?? null;
    } catch {
      return tokenError("invalid_request", 400);
    }
  }

  const expected = process.env.MCP_BEARER_SECRET?.trim();
  if (!expected) return tokenError("server_error", 500);

  if (grantType === "client_credentials") {
    if (!clientSecret) return tokenError("invalid_client", 401);
    if (clientSecret.length !== expected.length) return tokenError("invalid_client", 401);
    const match = crypto.timingSafeEqual(Buffer.from(clientSecret), Buffer.from(expected));
    if (!match) return tokenError("invalid_client", 401);

    return NextResponse.json({
      access_token: expected,
      token_type: "Bearer",
      expires_in: 86400,
    });
  }

  if (grantType === "authorization_code") {
    if (!code || !codeVerifier) return tokenError("invalid_request", 400);

    const parts = code.split(".");
    if (parts.length !== 2) return tokenError("invalid_grant", 400);

    const [payload, sig] = parts;

    // Verify HMAC signature
    const expectedSig = crypto
      .createHmac("sha256", expected)
      .update(payload)
      .digest("base64url");

    if (sig.length !== expectedSig.length) return tokenError("invalid_grant", 400);
    const sigMatch = crypto.timingSafeEqual(
      Buffer.from(sig),
      Buffer.from(expectedSig)
    );
    if (!sigMatch) return tokenError("invalid_grant", 400);

    // Decode and validate payload
    let parsed: { cc: string; exp: number };
    try {
      parsed = JSON.parse(Buffer.from(payload, "base64url").toString("utf8"));
    } catch {
      return tokenError("invalid_grant", 400);
    }

    if (!parsed.cc || !parsed.exp) return tokenError("invalid_grant", 400);
    if (Math.floor(Date.now() / 1000) > parsed.exp) return tokenError("invalid_grant", 400);

    // Verify PKCE: base64url(SHA256(code_verifier)) must equal code_challenge
    const verifierHash = crypto
      .createHash("sha256")
      .update(codeVerifier)
      .digest("base64url");

    if (verifierHash.length !== parsed.cc.length) return tokenError("invalid_grant", 400);
    const pkceMatch = crypto.timingSafeEqual(
      Buffer.from(verifierHash),
      Buffer.from(parsed.cc)
    );
    if (!pkceMatch) return tokenError("invalid_grant", 400);

    return NextResponse.json({
      access_token: expected,
      token_type: "Bearer",
      expires_in: 86400,
    });
  }

  return tokenError("unsupported_grant_type");
}
